version: '3.8'

services:
  sqlserver:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Thanhth@nh1"
      ACCEPT_EULA: "Y"
    networks:
      - internal
  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - sqlserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;encrypt=true;trustServerCertificate=true;databaseName=DB_AUCTION;
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Thanhth@nh1
    networks:
      - internal
networks:
  internal:
    name: internal

