name: Java CI with Maven and SQL Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - "1433:1433"
        env:
          SA_PASSWORD: ${{ secrets.SQL_SA_PASSWORD }}
          ACCEPT_EULA: "Y"

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Spring Boot application
      run: java -jar target/*.jar
