name: Spring Boot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - "1433:1433"
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Thanhth@nh1
          MSSQL_PID: Express

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create database
        run: |
          sqlcmd -S localhost -U sa -P Thanhth@nh1 -i db/init.sql

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Run unit tests
        run: mvn test
